import { AdapterSubscribe } from "./fakes/adapterSubscribe";
import { AdapterUnsubscribe } from "./fakes/adapterUnsubscribe";
import { ClearInterval } from "./fakes/clearInterval";
import { ClearSchedule } from "./fakes/clearSchedule";
import { ClearStateDelayed } from "./fakes/clearStateDelayed";
import { ClearTimeout } from "./fakes/clearTimeout";
import { CompareTime } from "./fakes/compareTime";
import { CreateState } from "./fakes/createState";
import { DeleteObject } from "./fakes/deleteObject";
import { DeleteState } from "./fakes/deleteState";
import { DelFile } from "./fakes/delFile";
import { Exec } from "./fakes/exec";
import { ExtendObject } from "./fakes/extendObject";
import { FormatDate } from "./fakes/formatDate";
import { FormatValue } from "./fakes/formatValue";
import { GetAttr } from "./fakes/getAttr";
import { GetAstroDate } from "./fakes/getAstroDate";
import { GetBinaryState } from "./fakes/getBinaryState";
import { GetDateObject } from "./fakes/getDateObject";
import { GetEnums } from "./fakes/getEnums";
import { GetHistory } from "./fakes/getHistory";
import { GetIdByName } from "./fakes/getIdByName";
import { GetObject } from "./fakes/getObject";
import { GetState } from "./fakes/getState";
import { GetStateDelayed } from "./fakes/getStateDelayed";
import { GetSubscriptions } from "./fakes/getSubscriptions";
import { Instance } from "./fakes/instance";
import { IsAstroDay } from "./fakes/isAstroDay";
import { IsScriptActive } from "./fakes/isScriptActive";
import { Log } from "./fakes/log";
import { MessageTo } from "./fakes/messageTo";
import { Name } from "./fakes/name";
import { On } from "./fakes/on";
import { OnLog } from "./fakes/onLog";
import { OnLogUnregister } from "./fakes/onLogUnregister";
import { OnMessage } from "./fakes/onMessage";
import { OnMessageUnregister } from "./fakes/onMessageUnregister";
import { OnStop } from "./fakes/onStop";
import { ReadFile } from "./fakes/readFile";
import { RunScript } from "./fakes/runScript";
import { Schedule } from "./fakes/schedule";
import { SendTo } from "./fakes/sendTo";
import { SendToHost } from "./fakes/sendToHost";
import { SetBinaryState } from "./fakes/setBinaryState";
import { SetInterval } from "./fakes/setInterval";
import { SetObject } from "./fakes/setObject";
import { SetState } from "./fakes/setState";
import { SetStateDelayed } from "./fakes/setStateDelayed";
import { SetTimeout } from "./fakes/setTimeout";
import { StartScript } from "./fakes/startScript";
import { StopScript } from "./fakes/stopScript";
import { Subscribe } from "./fakes/subscribe";
import { Unsubscribe } from "./fakes/unsubscribe";
import { WriteFile } from "./fakes/writeFile";

export interface IFakeApi {
    adapterSubscribe: AdapterSubscribe;
    adapterUnsubscribe: AdapterUnsubscribe;
    clearInterval: ClearInterval;
    clearSchedule: ClearSchedule;
    clearStateDelayed: ClearStateDelayed;
    clearTimeout: ClearTimeout;
    compareTime: CompareTime;
    createState: CreateState;
    deleteObject: DeleteObject;
    deleteState: DeleteState;
    delFile: DelFile;
    exec: Exec;
    extendObject: ExtendObject;
    formatDate: FormatDate;
    formatValue: FormatValue;
    getAttr: GetAttr;
    getAstroDate: GetAstroDate;
    getBinaryState: GetBinaryState;
    getDateObject: GetDateObject;
    getEnums: GetEnums;
    getHistory: GetHistory;
    getIdByName: GetIdByName;
    getObject: GetObject;
    getState: GetState;
    getStateDelayed: GetStateDelayed;
    getSubscriptions: GetSubscriptions;
    instance: Instance;
    isAstroDay: IsAstroDay;
    isScriptActive: IsScriptActive;
    log: Log;
    messageTo: MessageTo;
    name: Name;
    on: On;
    onLog: OnLog;
    onLogUnregister: OnLogUnregister;
    onMessage: OnMessage;
    onMessageUnregister: OnMessageUnregister;
    onStop: OnStop;
    readFile: ReadFile;
    runScript: RunScript;
    schedule: Schedule;
    sendTo: SendTo;
    sendToHost: SendToHost;
    setBinaryState: SetBinaryState;
    setInterval: SetInterval;
    setObject: SetObject;
    setState: SetState;
    setStateDelayed: SetStateDelayed;
    setTimeout: SetTimeout;
    startScript: StartScript;
    stopScript: StopScript;
    subscribe: Subscribe;
    unsubscribe: Unsubscribe;
    writeFile: WriteFile;
  }